import { MigrationInterface, QueryRunner } from "typeorm";

export class NombreDeTuMigracion1729548929798 implements MigrationInterface {
    name = 'NombreDeTuMigracion1729548929798'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "inmueble" DROP CONSTRAINT "fk_siniestro"`);
        await queryRunner.query(`ALTER TABLE "inmueble" DROP CONSTRAINT "fk_dependencia"`);
        await queryRunner.query(`ALTER TABLE "inmueble" DROP CONSTRAINT "fk_tipo_inmueble"`);
        await queryRunner.query(`ALTER TABLE "aeronave" DROP CONSTRAINT "fk_siniestro"`);
        await queryRunner.query(`ALTER TABLE "aeronave" DROP CONSTRAINT "fk_dependencia"`);
        await queryRunner.query(`ALTER TABLE "aeronave" DROP CONSTRAINT "fk_fabricante"`);
        await queryRunner.query(`ALTER TABLE "seguros" DROP CONSTRAINT "fk_dependencia"`);
        await queryRunner.query(`ALTER TABLE "seguros" DROP CONSTRAINT "fk_aseguradora"`);
        await queryRunner.query(`ALTER TABLE "seguros" DROP CONSTRAINT "fk_poliza"`);
        await queryRunner.query(`ALTER TABLE "seguros" DROP CONSTRAINT "fk_tipo_seguro"`);
        await queryRunner.query(`ALTER TABLE "seg_rc_usa" DROP CONSTRAINT "fk_dependencia"`);
        await queryRunner.query(`ALTER TABLE "seg_rc_usa" DROP CONSTRAINT "fk_aseguradora"`);
        await queryRunner.query(`ALTER TABLE "seg_rc_usa" DROP CONSTRAINT "fk_poliza"`);
        await queryRunner.query(`ALTER TABLE "seg_rc_usa" DROP CONSTRAINT "fk_tipo_seguro"`);
        await queryRunner.query(`ALTER TABLE "marca_vehiculo" RENAME COLUMN "id_marca" TO "Id_marca"`);
        await queryRunner.query(`ALTER SEQUENCE "marca_vehiculo_id_marca_seq" RENAME TO "marca_vehiculo_Id_marca_seq"`);
        await queryRunner.query(`ALTER TABLE "tipo_vehiculo" RENAME COLUMN "id_tipo_vehiculo" TO "Id_tipo_vehiculo"`);
        await queryRunner.query(`ALTER SEQUENCE "tipo_vehiculo_id_tipo_vehiculo_seq" RENAME TO "tipo_vehiculo_Id_tipo_vehiculo_seq"`);
        await queryRunner.query(`CREATE TABLE "institucion" ("id_institucion" SERIAL NOT NULL, "nombre" character varying(100) NOT NULL, "direccion" character varying NOT NULL, CONSTRAINT "PK_1431b8bf9b5c853b11d2ad27518" PRIMARY KEY ("id_institucion"))`);
        await queryRunner.query(`CREATE TABLE "aeronave_fabricante" ("id_fabricante_aeronave" SERIAL NOT NULL, "nombre" character varying(100) NOT NULL, "responsable" character varying(100) NOT NULL, CONSTRAINT "PK_611c912281b0986a0eafffbaa1d" PRIMARY KEY ("id_fabricante_aeronave"))`);
        await queryRunner.query(`CREATE TABLE "vehiculo" ("id_vehiculo" SERIAL NOT NULL, "numero_serie" character varying(50) NOT NULL, "modelo" integer NOT NULL, "placas" character varying(20) NOT NULL, "color" character varying(20) NOT NULL, "numero_cilindros" integer NOT NULL, "numero_activo_sap" character varying(50) NOT NULL, "dependenciaIdDependencia" integer NOT NULL, CONSTRAINT "UQ_edeec90c2f6a5397817b4f1c0aa" UNIQUE ("placas"), CONSTRAINT "PK_151f12779b5a696b17ace3e5806" PRIMARY KEY ("id_vehiculo"))`);
        await queryRunner.query(`CREATE TABLE "siniestro" ("id_siniestro" SERIAL NOT NULL, "fecha" character varying(100) NOT NULL, "descripcion" character varying(300) NOT NULL, "monto_reclamado" numeric NOT NULL, CONSTRAINT "PK_de94317ff4c5d46057cf3a62044" PRIMARY KEY ("id_siniestro"))`);
        await queryRunner.query(`CREATE TABLE "accidente_escolares" ("id_accescolar" SERIAL NOT NULL, "fecha" date NOT NULL, "dependenciaIdDependencia" integer, CONSTRAINT "PK_77ed50eb88156e711250e2bc15e" PRIMARY KEY ("id_accescolar"))`);
        await queryRunner.query(`CREATE TABLE "poliza" ("id_poliza" SERIAL NOT NULL, "numero_poliza" character varying(50) NOT NULL, "id_ramo_poliza" integer NOT NULL, "descripcion" character varying(200) NOT NULL, CONSTRAINT "PK_081388735a884572c89304228dd" PRIMARY KEY ("id_poliza"))`);
        await queryRunner.query(`CREATE TABLE "aseguradora" ("id_aseguradora" SERIAL NOT NULL, "nombre_aseguradora" character varying(100) NOT NULL, CONSTRAINT "PK_5a2bc7f56fc5f919aab2cbc0b5e" PRIMARY KEY ("id_aseguradora"))`);
        await queryRunner.query(`CREATE TABLE "dependencias" ("id_dependencia" SERIAL NOT NULL, "nombre" character varying(100) NOT NULL, "direccion" character varying NOT NULL, "telefono" integer NOT NULL, "email" character varying(100) NOT NULL, "responsable" character varying(100) NOT NULL, "accidentesEscolaresIdAccescolar" integer NOT NULL, CONSTRAINT "PK_4cfebed963000898d52e918ecb8" PRIMARY KEY ("id_dependencia"))`);
        await queryRunner.query(`CREATE TABLE "dependencias_institucion_institucion" ("dependenciasIdDependencia" integer NOT NULL, "institucionIdInstitucion" integer NOT NULL, CONSTRAINT "PK_a1a6e13650433bfd66cf7b84bc4" PRIMARY KEY ("dependenciasIdDependencia", "institucionIdInstitucion"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e58d588601fb96b917c6f6cdfa" ON "dependencias_institucion_institucion" ("dependenciasIdDependencia") `);
        await queryRunner.query(`CREATE INDEX "IDX_7e3fc3de8bc419ce076bc4e060" ON "dependencias_institucion_institucion" ("institucionIdInstitucion") `);
        await queryRunner.query(`ALTER TABLE "inmueble" DROP COLUMN "direcci¢n"`);
        await queryRunner.query(`ALTER TABLE "inmueble" DROP COLUMN "id_tipo_inmueble"`);
        await queryRunner.query(`ALTER TABLE "inmueble" DROP COLUMN "id_dependencia"`);
        await queryRunner.query(`ALTER TABLE "inmueble" DROP COLUMN "id_siniestro"`);
        await queryRunner.query(`ALTER TABLE "aeronave" DROP COLUMN "id_fabricante"`);
        await queryRunner.query(`ALTER TABLE "aeronave" DROP COLUMN "id_dependencia"`);
        await queryRunner.query(`ALTER TABLE "aeronave" DROP COLUMN "id_siniestro"`);
        await queryRunner.query(`ALTER TABLE "seguros" DROP COLUMN "id_tipo_seguro"`);
        await queryRunner.query(`ALTER TABLE "seguros" DROP COLUMN "id_poliza"`);
        await queryRunner.query(`ALTER TABLE "seguros" DROP COLUMN "id_aseguradora"`);
        await queryRunner.query(`ALTER TABLE "clientes" DROP CONSTRAINT "clientes_pkey"`);
        await queryRunner.query(`ALTER TABLE "clientes" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "tipo_inmueble" ADD "inmueblesIdInmueble" integer`);
        await queryRunner.query(`ALTER TABLE "inmueble" ADD "direccion" character varying(100) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "inmueble" ADD "tipoInmuebleIdInmueble" integer`);
        await queryRunner.query(`ALTER TABLE "inmueble" ADD "dependenciaIdDependencia" integer`);
        await queryRunner.query(`ALTER TABLE "inmueble" ADD "siniestroIdSiniestro" integer`);
        await queryRunner.query(`ALTER TABLE "aeronave" ADD "aeronaveFabricanteIdFabricanteAeronave" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "aeronave" ADD "dependenciaIdDependencia" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "seguros" ADD "tipoSeguroIdTipoSeguro" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "seguros" ADD "polizasIdPoliza" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "seguros" ADD "aseguradorasIdAseguradora" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "seguros" ADD "dependenciaIdDependencia" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "clientes" ADD "id_cliente" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "clientes" ADD CONSTRAINT "PK_4b7c4b981b60b5c6b1d04c84a54" PRIMARY KEY ("id_cliente")`);
        await queryRunner.query(`ALTER TABLE "inmueble" ALTER COLUMN "numero_activo_sap" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "aeronave" DROP COLUMN "numero_serie"`);
        await queryRunner.query(`ALTER TABLE "aeronave" ADD "numero_serie" character varying(20) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "aeronave" ALTER COLUMN "tipo" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "aeronave" DROP COLUMN "color"`);
        await queryRunner.query(`ALTER TABLE "aeronave" ADD "color" character varying(15) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "aeronave" DROP COLUMN "numero_activo_sap"`);
        await queryRunner.query(`ALTER TABLE "aeronave" ADD "numero_activo_sap" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ramo_poliza" DROP COLUMN "descripcion"`);
        await queryRunner.query(`ALTER TABLE "ramo_poliza" ADD "descripcion" character varying(200) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "seguros" DROP COLUMN "monto_cobertura"`);
        await queryRunner.query(`ALTER TABLE "seguros" ADD "monto_cobertura" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "seguros" ALTER COLUMN "id_dependencia" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "clientes" DROP COLUMN "direccion"`);
        await queryRunner.query(`ALTER TABLE "clientes" ADD "direccion" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "clientes" DROP COLUMN "telefono"`);
        await queryRunner.query(`ALTER TABLE "clientes" ADD "telefono" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "clientes" DROP CONSTRAINT "clientes_email_key"`);
        await queryRunner.query(`ALTER TABLE "clientes" DROP COLUMN "fecha_registro"`);
        await queryRunner.query(`ALTER TABLE "clientes" ADD "fecha_registro" date NOT NULL`);
        await queryRunner.query(`ALTER TABLE "rol" DROP COLUMN "descripcion"`);
        await queryRunner.query(`ALTER TABLE "rol" ADD "descripcion" character varying(200) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "seg_rc_usa" ALTER COLUMN "id_tipo_seguro" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "seg_rc_usa" ALTER COLUMN "id_poliza" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "seg_rc_usa" ALTER COLUMN "id_aseguradora" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "seg_rc_usa" DROP COLUMN "monto_cobertura"`);
        await queryRunner.query(`ALTER TABLE "seg_rc_usa" ADD "monto_cobertura" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "seg_rc_usa" ALTER COLUMN "id_dependencia" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tipo_inmueble" ADD CONSTRAINT "FK_73aae0a6ac8f95fa41a8761b034" FOREIGN KEY ("inmueblesIdInmueble") REFERENCES "inmueble"("id_inmueble") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inmueble" ADD CONSTRAINT "FK_dfe911e42d5dc721c9815951d57" FOREIGN KEY ("tipoInmuebleIdInmueble") REFERENCES "tipo_inmueble"("id_inmueble") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inmueble" ADD CONSTRAINT "FK_27539b059cb3384a097193d2d61" FOREIGN KEY ("dependenciaIdDependencia") REFERENCES "dependencias"("id_dependencia") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inmueble" ADD CONSTRAINT "FK_585cb2c78b826371d4631a53d3e" FOREIGN KEY ("siniestroIdSiniestro") REFERENCES "siniestro"("id_siniestro") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "vehiculo" ADD CONSTRAINT "FK_7f468a551df6e9e1acd98eb7887" FOREIGN KEY ("dependenciaIdDependencia") REFERENCES "dependencias"("id_dependencia") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "aeronave" ADD CONSTRAINT "FK_e5863ae0ccc1eddcac4c265f3f2" FOREIGN KEY ("aeronaveFabricanteIdFabricanteAeronave") REFERENCES "aeronave_fabricante"("id_fabricante_aeronave") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "aeronave" ADD CONSTRAINT "FK_009d11d433a56173560cca344ce" FOREIGN KEY ("dependenciaIdDependencia") REFERENCES "dependencias"("id_dependencia") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "accidente_escolares" ADD CONSTRAINT "FK_e07aed6b1457459765302f51845" FOREIGN KEY ("dependenciaIdDependencia") REFERENCES "dependencias"("id_dependencia") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "seguros" ADD CONSTRAINT "FK_6b030d040d66485e9651858e1dd" FOREIGN KEY ("tipoSeguroIdTipoSeguro") REFERENCES "tipo_seguro"("id_tipo_seguro") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "seguros" ADD CONSTRAINT "FK_76c07e4f8bf4b1348afb695c7de" FOREIGN KEY ("polizasIdPoliza") REFERENCES "poliza"("id_poliza") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "seguros" ADD CONSTRAINT "FK_1751481f612ced5cf388b7041f0" FOREIGN KEY ("aseguradorasIdAseguradora") REFERENCES "aseguradora"("id_aseguradora") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "seguros" ADD CONSTRAINT "FK_de4048caef06f32ee78dc79e519" FOREIGN KEY ("dependenciaIdDependencia") REFERENCES "dependencias"("id_dependencia") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "dependencias" ADD CONSTRAINT "FK_94693a4c8ad42fc5b321d03fee9" FOREIGN KEY ("accidentesEscolaresIdAccescolar") REFERENCES "accidente_escolares"("id_accescolar") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "dependencias_institucion_institucion" ADD CONSTRAINT "FK_e58d588601fb96b917c6f6cdfa8" FOREIGN KEY ("dependenciasIdDependencia") REFERENCES "dependencias"("id_dependencia") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "dependencias_institucion_institucion" ADD CONSTRAINT "FK_7e3fc3de8bc419ce076bc4e060b" FOREIGN KEY ("institucionIdInstitucion") REFERENCES "institucion"("id_institucion") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "dependencias_institucion_institucion" DROP CONSTRAINT "FK_7e3fc3de8bc419ce076bc4e060b"`);
        await queryRunner.query(`ALTER TABLE "dependencias_institucion_institucion" DROP CONSTRAINT "FK_e58d588601fb96b917c6f6cdfa8"`);
        await queryRunner.query(`ALTER TABLE "dependencias" DROP CONSTRAINT "FK_94693a4c8ad42fc5b321d03fee9"`);
        await queryRunner.query(`ALTER TABLE "seguros" DROP CONSTRAINT "FK_de4048caef06f32ee78dc79e519"`);
        await queryRunner.query(`ALTER TABLE "seguros" DROP CONSTRAINT "FK_1751481f612ced5cf388b7041f0"`);
        await queryRunner.query(`ALTER TABLE "seguros" DROP CONSTRAINT "FK_76c07e4f8bf4b1348afb695c7de"`);
        await queryRunner.query(`ALTER TABLE "seguros" DROP CONSTRAINT "FK_6b030d040d66485e9651858e1dd"`);
        await queryRunner.query(`ALTER TABLE "accidente_escolares" DROP CONSTRAINT "FK_e07aed6b1457459765302f51845"`);
        await queryRunner.query(`ALTER TABLE "aeronave" DROP CONSTRAINT "FK_009d11d433a56173560cca344ce"`);
        await queryRunner.query(`ALTER TABLE "aeronave" DROP CONSTRAINT "FK_e5863ae0ccc1eddcac4c265f3f2"`);
        await queryRunner.query(`ALTER TABLE "vehiculo" DROP CONSTRAINT "FK_7f468a551df6e9e1acd98eb7887"`);
        await queryRunner.query(`ALTER TABLE "inmueble" DROP CONSTRAINT "FK_585cb2c78b826371d4631a53d3e"`);
        await queryRunner.query(`ALTER TABLE "inmueble" DROP CONSTRAINT "FK_27539b059cb3384a097193d2d61"`);
        await queryRunner.query(`ALTER TABLE "inmueble" DROP CONSTRAINT "FK_dfe911e42d5dc721c9815951d57"`);
        await queryRunner.query(`ALTER TABLE "tipo_inmueble" DROP CONSTRAINT "FK_73aae0a6ac8f95fa41a8761b034"`);
        await queryRunner.query(`ALTER TABLE "seg_rc_usa" ALTER COLUMN "id_dependencia" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "seg_rc_usa" DROP COLUMN "monto_cobertura"`);
        await queryRunner.query(`ALTER TABLE "seg_rc_usa" ADD "monto_cobertura" numeric(10,2) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "seg_rc_usa" ALTER COLUMN "id_aseguradora" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "seg_rc_usa" ALTER COLUMN "id_poliza" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "seg_rc_usa" ALTER COLUMN "id_tipo_seguro" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "rol" DROP COLUMN "descripcion"`);
        await queryRunner.query(`ALTER TABLE "rol" ADD "descripcion" text`);
        await queryRunner.query(`ALTER TABLE "clientes" DROP COLUMN "fecha_registro"`);
        await queryRunner.query(`ALTER TABLE "clientes" ADD "fecha_registro" TIMESTAMP DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "clientes" ADD CONSTRAINT "clientes_email_key" UNIQUE ("email")`);
        await queryRunner.query(`ALTER TABLE "clientes" DROP COLUMN "telefono"`);
        await queryRunner.query(`ALTER TABLE "clientes" ADD "telefono" character varying(15)`);
        await queryRunner.query(`ALTER TABLE "clientes" DROP COLUMN "direccion"`);
        await queryRunner.query(`ALTER TABLE "clientes" ADD "direccion" text`);
        await queryRunner.query(`ALTER TABLE "seguros" ALTER COLUMN "id_dependencia" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "seguros" DROP COLUMN "monto_cobertura"`);
        await queryRunner.query(`ALTER TABLE "seguros" ADD "monto_cobertura" numeric(10,2) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ramo_poliza" DROP COLUMN "descripcion"`);
        await queryRunner.query(`ALTER TABLE "ramo_poliza" ADD "descripcion" text`);
        await queryRunner.query(`ALTER TABLE "aeronave" DROP COLUMN "numero_activo_sap"`);
        await queryRunner.query(`ALTER TABLE "aeronave" ADD "numero_activo_sap" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "aeronave" DROP COLUMN "color"`);
        await queryRunner.query(`ALTER TABLE "aeronave" ADD "color" character varying(20)`);
        await queryRunner.query(`ALTER TABLE "aeronave" ALTER COLUMN "tipo" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "aeronave" DROP COLUMN "numero_serie"`);
        await queryRunner.query(`ALTER TABLE "aeronave" ADD "numero_serie" character varying(50) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "inmueble" ALTER COLUMN "numero_activo_sap" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "clientes" DROP CONSTRAINT "PK_4b7c4b981b60b5c6b1d04c84a54"`);
        await queryRunner.query(`ALTER TABLE "clientes" DROP COLUMN "id_cliente"`);
        await queryRunner.query(`ALTER TABLE "seguros" DROP COLUMN "dependenciaIdDependencia"`);
        await queryRunner.query(`ALTER TABLE "seguros" DROP COLUMN "aseguradorasIdAseguradora"`);
        await queryRunner.query(`ALTER TABLE "seguros" DROP COLUMN "polizasIdPoliza"`);
        await queryRunner.query(`ALTER TABLE "seguros" DROP COLUMN "tipoSeguroIdTipoSeguro"`);
        await queryRunner.query(`ALTER TABLE "aeronave" DROP COLUMN "dependenciaIdDependencia"`);
        await queryRunner.query(`ALTER TABLE "aeronave" DROP COLUMN "aeronaveFabricanteIdFabricanteAeronave"`);
        await queryRunner.query(`ALTER TABLE "inmueble" DROP COLUMN "siniestroIdSiniestro"`);
        await queryRunner.query(`ALTER TABLE "inmueble" DROP COLUMN "dependenciaIdDependencia"`);
        await queryRunner.query(`ALTER TABLE "inmueble" DROP COLUMN "tipoInmuebleIdInmueble"`);
        await queryRunner.query(`ALTER TABLE "inmueble" DROP COLUMN "direccion"`);
        await queryRunner.query(`ALTER TABLE "tipo_inmueble" DROP COLUMN "inmueblesIdInmueble"`);
        await queryRunner.query(`ALTER TABLE "clientes" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "clientes" ADD CONSTRAINT "clientes_pkey" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "seguros" ADD "id_aseguradora" integer`);
        await queryRunner.query(`ALTER TABLE "seguros" ADD "id_poliza" integer`);
        await queryRunner.query(`ALTER TABLE "seguros" ADD "id_tipo_seguro" integer`);
        await queryRunner.query(`ALTER TABLE "aeronave" ADD "id_siniestro" integer`);
        await queryRunner.query(`ALTER TABLE "aeronave" ADD "id_dependencia" integer`);
        await queryRunner.query(`ALTER TABLE "aeronave" ADD "id_fabricante" integer`);
        await queryRunner.query(`ALTER TABLE "inmueble" ADD "id_siniestro" integer`);
        await queryRunner.query(`ALTER TABLE "inmueble" ADD "id_dependencia" integer`);
        await queryRunner.query(`ALTER TABLE "inmueble" ADD "id_tipo_inmueble" integer`);
        await queryRunner.query(`ALTER TABLE "inmueble" ADD "direcci¢n" text NOT NULL`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7e3fc3de8bc419ce076bc4e060"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e58d588601fb96b917c6f6cdfa"`);
        await queryRunner.query(`DROP TABLE "dependencias_institucion_institucion"`);
        await queryRunner.query(`DROP TABLE "dependencias"`);
        await queryRunner.query(`DROP TABLE "aseguradora"`);
        await queryRunner.query(`DROP TABLE "poliza"`);
        await queryRunner.query(`DROP TABLE "accidente_escolares"`);
        await queryRunner.query(`DROP TABLE "siniestro"`);
        await queryRunner.query(`DROP TABLE "vehiculo"`);
        await queryRunner.query(`DROP TABLE "aeronave_fabricante"`);
        await queryRunner.query(`DROP TABLE "institucion"`);
        await queryRunner.query(`ALTER SEQUENCE "tipo_vehiculo_Id_tipo_vehiculo_seq" RENAME TO "tipo_vehiculo_id_tipo_vehiculo_seq"`);
        await queryRunner.query(`ALTER TABLE "tipo_vehiculo" RENAME COLUMN "Id_tipo_vehiculo" TO "id_tipo_vehiculo"`);
        await queryRunner.query(`ALTER SEQUENCE "marca_vehiculo_Id_marca_seq" RENAME TO "marca_vehiculo_id_marca_seq"`);
        await queryRunner.query(`ALTER TABLE "marca_vehiculo" RENAME COLUMN "Id_marca" TO "id_marca"`);
        await queryRunner.query(`ALTER TABLE "seg_rc_usa" ADD CONSTRAINT "fk_tipo_seguro" FOREIGN KEY ("id_tipo_seguro", "id_tipo_seguro") REFERENCES "tipo_seguro"("id_tipo_seguro","id_tipo_seguro") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "seg_rc_usa" ADD CONSTRAINT "fk_poliza" FOREIGN KEY ("id_poliza", "id_poliza") REFERENCES "polizas"("id_poliza","id_poliza") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "seg_rc_usa" ADD CONSTRAINT "fk_aseguradora" FOREIGN KEY ("id_aseguradora", "id_aseguradora") REFERENCES "aseguradoras"("id_aseguradora","id_aseguradora") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "seg_rc_usa" ADD CONSTRAINT "fk_dependencia" FOREIGN KEY ("id_dependencia", "id_dependencia", "id_dependencia", "id_dependencia") REFERENCES "dependencia"("id_dependencia","id_dependencia","id_dependencia","id_dependencia") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "seguros" ADD CONSTRAINT "fk_tipo_seguro" FOREIGN KEY ("id_tipo_seguro", "id_tipo_seguro") REFERENCES "tipo_seguro"("id_tipo_seguro","id_tipo_seguro") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "seguros" ADD CONSTRAINT "fk_poliza" FOREIGN KEY ("id_poliza", "id_poliza") REFERENCES "polizas"("id_poliza","id_poliza") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "seguros" ADD CONSTRAINT "fk_aseguradora" FOREIGN KEY ("id_aseguradora", "id_aseguradora") REFERENCES "aseguradoras"("id_aseguradora","id_aseguradora") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "seguros" ADD CONSTRAINT "fk_dependencia" FOREIGN KEY ("id_dependencia", "id_dependencia", "id_dependencia", "id_dependencia") REFERENCES "dependencia"("id_dependencia","id_dependencia","id_dependencia","id_dependencia") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "aeronave" ADD CONSTRAINT "fk_fabricante" FOREIGN KEY ("id_fabricante") REFERENCES "fabricante_aeronave"("id_fabricante") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "aeronave" ADD CONSTRAINT "fk_dependencia" FOREIGN KEY ("id_dependencia", "id_dependencia", "id_dependencia", "id_dependencia") REFERENCES "dependencia"("id_dependencia","id_dependencia","id_dependencia","id_dependencia") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "aeronave" ADD CONSTRAINT "fk_siniestro" FOREIGN KEY ("id_siniestro", "id_siniestro") REFERENCES "siniestros"("id_siniestro","id_siniestro") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inmueble" ADD CONSTRAINT "fk_tipo_inmueble" FOREIGN KEY ("id_tipo_inmueble") REFERENCES "tipo_inmueble"("id_inmueble") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inmueble" ADD CONSTRAINT "fk_dependencia" FOREIGN KEY ("id_dependencia", "id_dependencia", "id_dependencia", "id_dependencia") REFERENCES "dependencia"("id_dependencia","id_dependencia","id_dependencia","id_dependencia") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inmueble" ADD CONSTRAINT "fk_siniestro" FOREIGN KEY ("id_siniestro", "id_siniestro") REFERENCES "siniestros"("id_siniestro","id_siniestro") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
